[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True
pretty = True

[mypy-models.*]
disallow_untyped_defs = False

[mypy-portfolio.*]
disallow_untyped_defs = False

[mypy-allocator.*]
disallow_untyped_defs = False
