[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True
pretty = True

[mypy-shared.models.*]
disallow_untyped_defs = False

[mypy-ducks.portfolio.*]
disallow_untyped_defs = False
